# Taps
tap "manaflow-ai/cmux"
tap "modem-dev/tap"

# CLI tools
brew "bat" # Output highlighting (better `cat`)
brew "btop" # Performance and resource monitoring tool (better `top`)
brew "eza" # Listing files with info (better `ls`)
brew "fastfetch" # Show pretty system info
brew "fd" # Find entries in your filesystem (better `find`)
brew "fnm" # Node.js version manager
brew "fzf" # Fuzzy file finder and filtering
brew "gh" # GitHub CLI: interact with GitHub PRs, issues, repos
brew "git" # Version control
brew "gitleaks" # Audit git repos for secrets
brew "gnupg" # Encryption and signing capabilities for data verification
brew "pnpm" # Efficient Node.js package manager
brew "prettyping" # Prettier and compact `ping`
brew "python" # For Python work or node module builds
brew "ripgrep" # Searching within files (better `grep`)
brew "shellcheck" # Shell scripts linting
brew "sops" # Secrets manager
brew "starship" # Prompt manager
brew "tlrc" # Community-maintained docs (better `man`)
brew "trash-cli", link: true # Record and restore removed files (better `rm`)
brew "webp" # More efficient web images
brew "zoxide" # Convenient and magical navigation (better `cd`)
brew "zsh" # A shell of choice
brew "zsh-autosuggestions" # Fish-like autosuggestions for Zsh
brew "zsh-fast-syntax-highlighting" # Feature-rich syntax highlighting for Zsh
brew "modem-dev/tap/hunk" # Review-first terminal diff viewer (better `diff`)

# Fonts
cask "font-meslo-lg-nerd-font"

# GUI apps
cask "cmux" # Multitasking terminal to orchestrate agents
cask "dash" # API documentation reader
cask "ghostty" # Better terminal emulator for regular operating
cask "helium-browser" # Privacy-first browser for testing
cask "hiddenbar" # Manage menu bar icons
cask "keka" # File archiver and extractor
cask "marta" # File manager
cask "obsidian" # Main note taking app
cask "optimage" # Image optimization
cask "orbstack" # Docker alternative
cask "pearcleaner" # Clean up macOS from junk and apps leftovers
cask "raycast" # All-in-one app / tasks launcher
cask "signal" # Messenger
cask "visual-studio-code" # Main code editor
cask "whatsapp" # Messenger

# VS Code extensions
vscode "bierner.markdown-preview-github-styles"
vscode "bradlc.vscode-tailwindcss"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.vscode-pull-request-github"
vscode "ms-azuretools.vscode-containers" # Auto-installed by Docker extension
vscode "ms-azuretools.vscode-docker"
vscode "naumovs.color-highlight"
vscode "oxc.oxc-vscode"
vscode "redhat.vscode-yaml"
vscode "sapegin.icons-squirrelppuccinlight"
vscode "sapegin.just-blame"
vscode "sapegin.mini-markdown"
vscode "sapegin.theme-squirrelsonglight"
vscode "sapegin.todo-tomorrow"
vscode "sleistner.vscode-fileutils"
vscode "streetsidesoftware.code-spell-checker"
vscode "tekumara.typos-vscode"
vscode "usernamehw.errorlens"
